# Assignment

Q1. Write the NumPy program to create an array of ones and an array
of zeros?

    Expected OutputCreate an array of zeros
    Default type is float
    [[ 0. 0.]]
    Type changes to int
    [[0 0]]
    Create an array of ones
    Default type is float
    [[ 1. 1.]]
    Type changes to int
    [[1 1]]

In [15]:
import numpy as np
print(np.zeros((1,2)))

print(np.zeros((1,2),dtype=int))

print(np.ones((1,2)))
print(np.ones((1,2), dtype=int))

[[0. 0.]]
[[0 0]]
[[1. 1.]]
[[1 1]]


Q2. Write the NumPy program to change the dimension of an array?

    Expected Output6 rows and 0 columns
    (6,)
    (3, 3) -> 3 rows and 3 columns
    [[1 2 3]
    [4 5 6]
    [7 8 9]]
    Change array shape to (3, 3) -> 3 rows and 3 columns
    [[1 2 3]
    [4 5 6]
    [7 8 9]]

In [41]:
x=np.array([1 ,2 ,3,4, 5 ,6,7,8,9])

y= x.reshape(3,3)
print(y)

(9,)
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q3. Write the NumPy program to create a new shape to an array
without changing its data ?

    Reshape 3x2-
    [[1 2]
    [3 4]
    [5 6]]
    Reshape 2x3-
    [[1 2 3]
    [4 5 6]]

In [54]:
x1= np.array([[[1 ,2],[3 ,4],[5, 6]]])
x1
print(x1.reshape(2,3))


[[1 2 3]
 [4 5 6]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


Q4. Write the NumPy program to create a new array of 3*5, filled with
2?

    Expected Output-
    [[2 2 2 2 2]
    [2 2 2 2 2]
    [2 2 2 2 2]]
    [[2 2 2 2 2]
    [2 2 2 2 2]
    [2 2 2 2 2]]

In [56]:
print(2*np.ones((3,5), dtype=int))

x = np.full((3, 5), 2, dtype=np.uint)
print(x)



[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


Q5. Write the NumPy program to create a 3-D array with ones on a
diagonal and zeros elsewhere?

    Expected Output-
    [[ 1. 0. 0.]
    [ 0. 1. 0.]
    [ 0. 0. 1.]]

In [63]:

np.diagflat([1,1,1])


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Q6. Write the NumPy program to split an array of 14 elements into the
3 arrays and each of which has 2, 4, and 8 elements in original
order?

    Expected OutputOriginal array- [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
    After splitting-
    [array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [68]:

x = np.arange(1, 15)
print(x)
print(np.split(x, [2, 6]))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


Q7. Write the NumPy program to split of an array of shape 4x4 it into
two arrays along the second axis ?

    Sample array -
    [[ 0 1 2 3]
    [ 4 5 6 7]
    [ 8 9 10 11]
    [12 13 14 15]]
    Expected Output-
    [array([[ 0, 1],
    [ 4, 5],
    [ 8, 9],
    [12, 13]]), array([[ 2, 3],
    [ 6, 7],
    [10, 11],
    [14, 15]]), array([], shape=(4, 0), dtype=int64)]

Q8. Write the NumPy program to create a 5x5 matrix with row values
ranging from 0 to 4?

    Original array-
    [[ 0. 0. 0. 0. 0.]
    [ 0. 0. 0. 0. 0.]
    [ 0. 0. 0. 0. 0.]
    [ 0. 0. 0. 0. 0.]
    [ 0. 0. 0. 0. 0.]]
    Row values ranging from 0 to 4.
    [[ 0. 1. 2. 3. 4.]
    [ 0. 1. 2. 3. 4.]
    [ 0. 1. 2. 3. 4.]
    [ 0. 1. 2. 3. 4.]
    [ 0. 1. 2. 3. 4.]]

In [95]:
v1= np.zeros((5,5))
v1[:]=np.arange(5)
v1

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

Q9. Write the NumPy program to create an array of zeros and three
column types (integer, float, character)?

    Expected Output-
    [(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
    (3, 3., b'Gertrude B. Elion')]

In [107]:
import numpy as np
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data

print(x)


[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


Q10. Write the NumPy program to remove the negative values in the
numpy array with 0?

    Expected OutputOriginal array:
    [-1 -4 0 2 3 4 5 -6]
    Replace the negative values of the said array with 0-
    [0 0 0 2 3 4 5 0]

In [115]:
r1=np.array([-1, -4 ,0 ,2 ,3 ,4 ,5 ,-6])
print(r1)
r1[:2,]=0
r1

[-1 -4  0  2  3  4  5 -6]


array([ 0,  0,  0,  2,  3,  4,  5, -6])

Q11. Write the NumPy program to compute the histogram of a set of
data?

Q12. Write the NumPy program to compute the line graph of a set of
data?

Q13. Write the NumPy program to extracts all the elements from second
row from given (4x4) array?
    
    Sample OutputOriginal array-
    [[ 0 1 2 3]
    [ 4 5 6 7]
    [ 8 9 10 11]
    [12 13 14 15]]
    Extracted data- Second row
    [4 5 6 7]

In [84]:
x4=np.arange(16)

x5=x4.reshape(4,4)
x5[1,]

array([4, 5, 6, 7])

Q14. Write the NumPy program to extract first element of the second
row and fourth element of fourth row from a given (4x4) array?

    Sample OutputOriginal array-
    [[ 0 1 2 3]
    [ 4 5 6 7]
    [ 8 9 10 11]
    [12 13 14 15]]
    Extracted data- First element of the second row and fourth element of fourth row
    [ 4 15]


In [138]:
i1=np.arange(16)
u=i1.reshape(4,4)
u[[1,3],[0,3]]



array([ 4, 15])

Q15. Write the NumPy program to add two arrays A and B of sizes (3,3)
and (,3)?

    Sample OutputOriginal arrayArray-1
    [[1 1 1]
    [1 1 1]
    [1 1 1]]
    Array-2
    [0 1 2]
    A + B:
    [[1 2 3]
    [1 2 3]
    [1 2 3]]

In [89]:
c1= np.ones((3,3), dtype=int)
c2= np.arange(3)
c3=c2+c1
c3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Q16. Write the NumPy program to copy data from a given array to
another array?

    Sample OutputOriginal array-
    [24 27 30 29 18 14]
    Copy of the said array-
    [24 27 30 29 18 14]

In [70]:

x3=np.array([24, 27, 30, 29, 18, 14])

x4=x3.copy()
print(x4)

[24 27 30 29 18 14]


Q17. Write the NumPy program to calculate the sum of all columns of
the 2D numpy array?
    
    Sample OutputOriginal array-
    [[ 0 1 2 3 4 5 6 7 8]
    [ 9 10 11 12 13 14 15 16 17]
    [18 19 20 21 22 23 24 25 26]
    [27 28 29 30 31 32 33 34 35]]
    Sum of all columns-
    [54 58 62 66 70 74 78 82 86]

Q18. Write the NumPy program to calculate averages without NaNs
along the given array?
    
    Sample OutputOriginal array-
    [[10. 20. 30.]
    [40. 50. nan]
    [nan 6. nan]
    [nan nan nan]]
    Averages without NaNs along the said array-
    [20. 45. 6. nan]

## Great Job!